export const GET_GLOBAL_SUMMARY = "GET_GLOBAL_SUMMARY";
export const GET_GLOBAL_SUMMARY_SUCCESS = "GET_GLOBAL_SUMMARY_SUCCESS";
export const GET_GLOBAL_SUMMARY_FAIL = "GET_GLOBAL_SUMMARY_FAIL";

export const GET_SEARCH_RESULTS = "GET_SEARCH_RESULTS";
export const GET_SEARCH_RESULTS_SUCCESS = "GET_SEARCH_RESULTS_SUCCESS";
export const GET_SEARCH_RESULTS_FAIL = "GET_SEARCH_RESULTS_FAIL";

export const SORT_FROM_LOWEST = "SORT_FROM_LOWEST";
export const SORT_FROM_LOWEST_SUCCESS = "SORT_FROM_LOWEST_SUCCESS";
export const SORT_FROM_LOWEST_FAIL = "SORT_FROM_LOWEST_FAIL";

export const SORT_FROM_HIGHEST = "SORT_FROM_HIGHEST";
export const SORT_FROM_HIGHEST_SUCCESS = "SORT_FROM_HIGHEST_SUCCESS";
export const SORT_FROM_HIGHEST_FAIL = "SORT_FROM_HIGHEST_FAIL";
